import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./Header";
import "../styles/index.module.css"
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://img.icons8.com/win10/512/FFFFFF/tesla-logo.png" />
      </Head>
      <Header isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen}/>
    </>
  );
}
