import { useState } from "react";
import Header from "./Header";
import Head from "next/head";
import Menu from "./Menu";
import "../styles/index.module.css"



export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://img.icons8.com/win10/512/FFFFFF/tesla-logo.png" />
      </Head>
      <Header isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen}/>
      {!isMenuOpen && <Menu />}
    </>
  );
}
